#pragma once
#define WM_NOTIFICATION (WM_USER + 100)
#define HOTKEY_LEFT 1
#define HOTKEY_DOWN 2
#define HOTKEY_UP 3
#define HOTKEY_RIGHT 4
#define HOTKEY_MINIMIZE 5
#define HOTKEY_RESTORE 6
#define HOTKEY_MAXIMIZE 7

#define MENU_ACTIVATE 0x1
#define MENU_EXIT 0x2

#define NO_MINIMIZED_WINDOW 0x002

#define UNKNOWN_HOTKEY 0x2
